-- Optional manual upgrade for an existing AARPIVA Neon database.
-- The API also creates these structures at startup.
CREATE TABLE IF NOT EXISTS "PasswordResetOtps" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" integer NOT NULL,
    "OtpHash" text NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "Attempts" integer NOT NULL DEFAULT 0,
    "Used" boolean NOT NULL DEFAULT FALSE,
    "CreatedAt" timestamp with time zone NOT NULL
);
CREATE INDEX IF NOT EXISTS "IX_PasswordResetOtps_UserId_Used_ExpiresAt" ON "PasswordResetOtps" ("UserId", "Used", "ExpiresAt");
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "TermsAcceptedAt" timestamp with time zone NULL;
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "TermsVersion" text NULL;
