-- AARPIVA delivery pricing settings
-- Safe to run more than once.

CREATE TABLE IF NOT EXISTS "AppSettings" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Key" text NOT NULL,
    "Value" numeric(12,2) NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_AppSettings_Key" ON "AppSettings" ("Key");

ALTER TABLE "Orders" ADD COLUMN IF NOT EXISTS "Subtotal" numeric(12,2) NOT NULL DEFAULT 0;
ALTER TABLE "Orders" ADD COLUMN IF NOT EXISTS "DiscountAmount" numeric(12,2) NOT NULL DEFAULT 0;
ALTER TABLE "Orders" ADD COLUMN IF NOT EXISTS "DeliveryCharge" numeric(12,2) NOT NULL DEFAULT 0;

INSERT INTO "AppSettings" ("Key", "Value", "UpdatedAt") VALUES ('DeliveryCharge', 99, NOW()) ON CONFLICT ("Key") DO NOTHING;
INSERT INTO "AppSettings" ("Key", "Value", "UpdatedAt") VALUES ('FreeDeliveryThreshold', 1499, NOW()) ON CONFLICT ("Key") DO NOTHING;

UPDATE "Orders" o
SET "Subtotal" = COALESCE((SELECT SUM(i."UnitPrice" * i."Quantity") FROM "OrderItems" i WHERE i."OrderId" = o."Id"), 0),
    "DiscountAmount" = 0,
    "DeliveryCharge" = GREATEST(o."TotalAmount" - COALESCE((SELECT SUM(i."UnitPrice" * i."Quantity") FROM "OrderItems" i WHERE i."OrderId" = o."Id"), 0), 0)
WHERE o."Subtotal" = 0 AND o."TotalAmount" > 0;
