-- AARPIVA: server-side customer cart.
-- Safe for the current V1 database: creates the table only when missing.

CREATE TABLE IF NOT EXISTS "CartItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" integer NOT NULL,
    "ProductId" integer NOT NULL,
    "Quantity" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "FK_CartItems_Users_UserId"
        FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CartItems_Products_ProductId"
        FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE RESTRICT
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_CartItems_UserId_ProductId"
    ON "CartItems" ("UserId", "ProductId");

CREATE INDEX IF NOT EXISTS "IX_CartItems_ProductId"
    ON "CartItems" ("ProductId");
