using System.Text;
using System.Text.Json.Serialization;
using System.Threading.RateLimiting;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.HttpOverrides;
using Microsoft.AspNetCore.RateLimiting;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using SareeStore.Api.Data;
using SareeStore.Api.Models;
using SareeStore.Api.Services;

var builder = WebApplication.CreateBuilder(args);
var cfg = builder.Configuration;

var connectionString = cfg.GetConnectionString("DefaultConnection");
if (string.IsNullOrWhiteSpace(connectionString))
    throw new InvalidOperationException("ConnectionStrings:DefaultConnection is required.");

builder.Services.AddDbContext<AppDbContext>(o => o.UseNpgsql(connectionString));
builder.Services.AddHttpClient("razorpay", c =>
    c.BaseAddress = new Uri(cfg["Razorpay:ApiBaseUrl"] ?? "https://api.razorpay.com/v1"));
builder.Services.AddHttpClient("brevo", c => c.BaseAddress = new Uri("https://api.brevo.com"));
builder.Services.AddScoped<IEmailSender, EmailSender>();
builder.Services.AddScoped<INotificationService, NotificationService>();
builder.Services.AddScoped<IRazorpayService, RazorpayService>();
builder.Services.AddSingleton<IR2StorageService, R2StorageService>();

builder.Services.AddControllers().AddJsonOptions(o =>
{
    o.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter());
});

builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();
builder.Services.AddProblemDetails();
builder.Services.AddHealthChecks().AddDbContextCheck<AppDbContext>();

var allowedOrigins = (cfg["FrontendUrl"] ?? "http://localhost:4200")
    .Split(';', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
builder.Services.AddCors(o => o.AddPolicy("frontend", p => p
    .WithOrigins(allowedOrigins)
    .AllowAnyHeader()
    .AllowAnyMethod()
    .AllowCredentials()));

var jwtKey = cfg["Jwt:Key"];
if (string.IsNullOrWhiteSpace(jwtKey) || Encoding.UTF8.GetByteCount(jwtKey) < 32)
    throw new InvalidOperationException("Jwt:Key must be configured with at least 32 UTF-8 bytes.");

builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer(o =>
{
    o.TokenValidationParameters = new TokenValidationParameters
    {
        ValidateIssuer = true,
        ValidateAudience = true,
        ValidateLifetime = true,
        ValidateIssuerSigningKey = true,
        ValidIssuer = cfg["Jwt:Issuer"],
        ValidAudience = cfg["Jwt:Audience"],
        IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(jwtKey)),
        ClockSkew = TimeSpan.FromSeconds(30)
    };
});

builder.Services.AddAuthorization(o => o.AddPolicy("Admin", p => p.RequireRole(nameof(UserRole.Admin))));

builder.Services.AddRateLimiter(options =>
{
    options.AddPolicy("auth", context => RateLimitPartition.GetFixedWindowLimiter(
        context.Connection.RemoteIpAddress?.ToString() ?? "unknown",
        _ => new FixedWindowRateLimiterOptions
        {
            PermitLimit = 20,
            Window = TimeSpan.FromMinutes(1),
            QueueLimit = 0
        }));
    options.RejectionStatusCode = StatusCodes.Status429TooManyRequests;
});

static async Task EnsureEmailVerificationOtpSchemaAsync(AppDbContext db)
{
    await db.Database.ExecuteSqlRawAsync("""
        CREATE TABLE IF NOT EXISTS "EmailVerificationOtps" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "UserId" integer NOT NULL,
            "OtpHash" text NOT NULL,
            "ExpiresAt" timestamp with time zone NOT NULL,
            "Attempts" integer NOT NULL DEFAULT 0,
            "Used" boolean NOT NULL DEFAULT FALSE,
            "CreatedAt" timestamp with time zone NOT NULL
        );
        CREATE INDEX IF NOT EXISTS "IX_EmailVerificationOtps_UserId_Used_ExpiresAt" ON "EmailVerificationOtps" ("UserId", "Used", "ExpiresAt");
    """);
}

static async Task EnsurePasswordResetOtpSchemaAsync(AppDbContext db)
{
    await db.Database.ExecuteSqlRawAsync("""
        CREATE TABLE IF NOT EXISTS "PasswordResetOtps" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "UserId" integer NOT NULL,
            "OtpHash" text NOT NULL,
            "ExpiresAt" timestamp with time zone NOT NULL,
            "Attempts" integer NOT NULL DEFAULT 0,
            "Used" boolean NOT NULL DEFAULT FALSE,
            "CreatedAt" timestamp with time zone NOT NULL
        );
        CREATE INDEX IF NOT EXISTS "IX_PasswordResetOtps_UserId_Used_ExpiresAt" ON "PasswordResetOtps" ("UserId", "Used", "ExpiresAt");
    """);
}

static async Task EnsureLegalSchemaAsync(AppDbContext db)
{
    await db.Database.ExecuteSqlRawAsync("""
        ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "TermsAcceptedAt" timestamp with time zone NULL;
        ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "TermsVersion" text NULL;
    """);
}

static async Task EnsureCategoryImageSchemaAsync(AppDbContext db)
{
    await db.Database.ExecuteSqlRawAsync("""
        ALTER TABLE "Categories" ADD COLUMN IF NOT EXISTS "ImageMode" text NOT NULL DEFAULT 'auto';
        ALTER TABLE "Categories" ADD COLUMN IF NOT EXISTS "ImageUrl" text NULL;
        UPDATE "Categories" SET "ImageMode" = 'auto' WHERE "ImageMode" IS NULL OR BTRIM("ImageMode") = '';
        ALTER TABLE "Categories" ALTER COLUMN "ImageMode" SET DEFAULT 'auto';
        ALTER TABLE "Categories" ALTER COLUMN "ImageMode" SET NOT NULL;
    """);
}


static async Task EnsureCartSchemaAsync(AppDbContext db)
{
    await db.Database.ExecuteSqlRawAsync("""
        CREATE TABLE IF NOT EXISTS "CartItems" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "UserId" integer NOT NULL,
            "ProductId" integer NOT NULL,
            "Quantity" integer NOT NULL,
            "CreatedAt" timestamp with time zone NOT NULL,
            "UpdatedAt" timestamp with time zone NOT NULL,
            CONSTRAINT "FK_CartItems_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE,
            CONSTRAINT "FK_CartItems_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE RESTRICT
        );
        CREATE UNIQUE INDEX IF NOT EXISTS "IX_CartItems_UserId_ProductId" ON "CartItems" ("UserId", "ProductId");
        CREATE INDEX IF NOT EXISTS "IX_CartItems_ProductId" ON "CartItems" ("ProductId");
    """);
}

static async Task EnsureDeliveryPricingSchemaAsync(AppDbContext db)
{
    await db.Database.ExecuteSqlRawAsync("""
        CREATE TABLE IF NOT EXISTS "AppSettings" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "Key" text NOT NULL,
            "Value" numeric(12,2) NOT NULL,
            "UpdatedAt" timestamp with time zone NOT NULL
        );
        CREATE UNIQUE INDEX IF NOT EXISTS "IX_AppSettings_Key" ON "AppSettings" ("Key");
        ALTER TABLE "Orders" ADD COLUMN IF NOT EXISTS "Subtotal" numeric(12,2) NOT NULL DEFAULT 0;
        ALTER TABLE "Orders" ADD COLUMN IF NOT EXISTS "DiscountAmount" numeric(12,2) NOT NULL DEFAULT 0;
        ALTER TABLE "Orders" ADD COLUMN IF NOT EXISTS "DeliveryCharge" numeric(12,2) NOT NULL DEFAULT 0;
        INSERT INTO "AppSettings" ("Key", "Value", "UpdatedAt") VALUES ('DeliveryCharge', 99, NOW()) ON CONFLICT ("Key") DO NOTHING;
        INSERT INTO "AppSettings" ("Key", "Value", "UpdatedAt") VALUES ('FreeDeliveryThreshold', 1499, NOW()) ON CONFLICT ("Key") DO NOTHING;
    """);

    await db.Database.ExecuteSqlRawAsync("""
        UPDATE "Orders" o
        SET "Subtotal" = COALESCE((SELECT SUM(i."UnitPrice" * i."Quantity") FROM "OrderItems" i WHERE i."OrderId" = o."Id"), 0),
            "DiscountAmount" = 0,
            "DeliveryCharge" = GREATEST(o."TotalAmount" - COALESCE((SELECT SUM(i."UnitPrice" * i."Quantity") FROM "OrderItems" i WHERE i."OrderId" = o."Id"), 0), 0)
        WHERE o."Subtotal" = 0 AND o."TotalAmount" > 0;
    """);
}

static async Task EnsureReturnRequestSchemaAsync(AppDbContext db)
{
    await db.Database.ExecuteSqlRawAsync("""
        CREATE TABLE IF NOT EXISTS "ReturnRequests" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "OrderId" integer NOT NULL,
            "OrderItemId" integer NOT NULL,
            "UserId" integer NOT NULL,
            "Quantity" integer NOT NULL,
            "Reason" text NOT NULL,
            "Status" text NOT NULL DEFAULT 'Requested',
            "AdminNote" text NOT NULL DEFAULT '',
            "CreatedAt" timestamp with time zone NOT NULL,
            "UpdatedAt" timestamp with time zone NOT NULL
        );
        CREATE INDEX IF NOT EXISTS "IX_ReturnRequests_OrderId_OrderItemId_Status" ON "ReturnRequests" ("OrderId", "OrderItemId", "Status");
    """);
}

var app = builder.Build();

app.UseExceptionHandler(errorApp =>
{
    errorApp.Run(async context =>
    {
        context.Response.StatusCode = StatusCodes.Status500InternalServerError;
        await Results.Problem(
            statusCode: StatusCodes.Status500InternalServerError,
            title: "Unexpected server error.")
            .ExecuteAsync(context);
    });
});

app.UseForwardedHeaders(new ForwardedHeadersOptions
{
    ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
});

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseCors("frontend");
app.UseRateLimiter();
app.UseAuthentication();
app.UseAuthorization();

app.MapHealthChecks("/health").AllowAnonymous();
app.MapControllers();

using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
    await db.Database.EnsureCreatedAsync();
    await EnsureCategoryImageSchemaAsync(db);
    await EnsureEmailVerificationOtpSchemaAsync(db);
    await EnsurePasswordResetOtpSchemaAsync(db);
    await EnsureLegalSchemaAsync(db);
    await EnsureReturnRequestSchemaAsync(db);
    await EnsureCartSchemaAsync(db);
    await EnsureDeliveryPricingSchemaAsync(db);

    var adminEmail = cfg["SeedAdmin:Email"];
    var adminPassword = cfg["SeedAdmin:Password"];
    if (!string.IsNullOrWhiteSpace(adminEmail) && !string.IsNullOrWhiteSpace(adminPassword))
    {
        var normalizedAdmin = adminEmail.Trim().ToLowerInvariant();
        var admin = await db.Users.FirstOrDefaultAsync(x => x.Email == normalizedAdmin);
        if (admin is null)
        {
            db.Users.Add(new AppUser
            {
                Name = "Store Admin",
                Email = normalizedAdmin,
                PasswordHash = PasswordHasher.Hash(adminPassword),
                IsEmailVerified = true,
                Role = UserRole.Admin
            });
            await db.SaveChangesAsync();
        }
    }
}

app.Run();
